language: go

go:
  - 1.4
  - tip

before_install:
  - sudo apt-get install libmpg123-dev libao-dev make pkg-config -qq > apt-get.out 2>&1 || (cat apt-get.out && exit 1)
  - sudo git clone https://github.com/gypified/libmpg123.git 
  - cd libmpg123
  - sudo ./configure && sudo make && sudo make install

install:
  - go get github.com/beyondblog/go-mpg123
